services:
  postgres:
    container_name: cnc-matches
    image: postgres:12.1-alpine
    ports:
      - '5444:5432'
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: cnc-matches
    volumes:
      # copy the sql script to create tables
      - ./dbsetup.sql:/docker-entrypoint-initdb.d/dbsetup.sql
